version: "3.9"

services:

  meilisearch:
    image: getmeili/meilisearch:v1.7
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: "mysecret"   # change in production
    ports:
      - "7700:7700"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"

  backend:
    build: ./backend
    environment:
      PORT: 8080
      MEILI_HOST: http://meilisearch:7700
      MEILI_API_KEY: mysecret
      QDRANT_URL: http://qdrant:6333
      QDRANT_API_KEY: none
      GROQ_API_KEY: ${GROQ_API_KEY}
    depends_on:
      - meilisearch
      - qdrant
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"
